#!/usr/bin/env python3
"""Generate MkDocs abbreviation definitions from the project glossary CSV."""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


class GlossaryGenerationError(Exception):
    """A glossary input error with an actionable message."""


def repository_root() -> Path:
    return Path(__file__).resolve().parents[1]


def normalise_whitespace(value: str | None) -> str:
    return " ".join((value or "").split())


def title_case_variant(term: str) -> str:
    """Capitalise each word while preserving the casing of remaining letters."""
    return " ".join(word[:1].upper() + word[1:] for word in term.split(" "))


def parse_arguments() -> argparse.Namespace:
    root = repository_root()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=root / "glossary" / "working_version.csv")
    parser.add_argument("--output", type=Path, default=root / "docs" / "includes" / "glossary.md")
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    try:
        with arguments.input.open(encoding="utf-8-sig", newline="") as file:
            rows = list(csv.DictReader(file))
    except OSError as error:
        raise GlossaryGenerationError(f"Cannot read glossary CSV: {error}") from error

    canonical_terms: set[str] = set()
    definitions: dict[str, str] = {}
    for row_number, row in enumerate(rows, start=2):
        fields = {normalise_whitespace(key): value for key, value in row.items() if key}
        term = normalise_whitespace(fields.get("skos:prefLabel@en"))
        definition = normalise_whitespace(fields.get("skos:definition@en"))
        if not term or not definition:
            raise GlossaryGenerationError(
                f"Row {row_number} must contain an English label and definition."
            )
        if "[" in term or "]" in term:
            raise GlossaryGenerationError(
                f"Row {row_number} has a term unsupported by Markdown abbreviations: {term!r}"
            )
        canonical_key = term.casefold()
        if canonical_key in canonical_terms:
            raise GlossaryGenerationError(f"Duplicate English term after normalisation: {term!r}")
        canonical_terms.add(canonical_key)
        definitions[term] = definition

        # Python-Markdown's abbr extension is case-sensitive. Add common
        # sentence and heading forms without changing the canonical CSV label.
        for variant in (term[:1].upper() + term[1:], title_case_variant(term)):
            if variant != term:
                definitions[variant] = definition

    output = arguments.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    entries = sorted(
        (f"*[{term}]: {definition}" for term, definition in definitions.items()),
        key=lambda item: (-len(item.split("]:", 1)[0]), item.casefold()),
    )
    output.write_text(
        "<!-- Generated by scripts/generate_glossary_abbreviations.py; do not edit directly. -->\n\n"
        + "\n".join(entries)
        + "\n",
        encoding="utf-8",
    )
    print(f"Generated {len(entries)} glossary abbreviations in {output}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GlossaryGenerationError as error:
        print(f"Glossary generation failed: {error}", file=sys.stderr)
        raise SystemExit(1) from error
